BEGIN;

ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS devs INTEGER NOT NULL DEFAULT 0 CHECK (devs >= 0 AND devs <= 100),
  ADD COLUMN IF NOT EXISTS analysts INTEGER NOT NULL DEFAULT 0 CHECK (analysts >= 0 AND analysts <= 100),
  ADD COLUMN IF NOT EXISTS devops INTEGER NOT NULL DEFAULT 0 CHECK (devops >= 0 AND devops <= 100),
  ADD COLUMN IF NOT EXISTS designers INTEGER NOT NULL DEFAULT 0 CHECK (designers >= 0 AND designers <= 100),
  ADD COLUMN IF NOT EXISTS testers INTEGER NOT NULL DEFAULT 0 CHECK (testers >= 0 AND testers <= 100);

COMMIT;

